### ISSUE TITLE
Is the app a "fake" or a "bad block" tester?

### ISSUE THREAD

**Issue by lexterror** [c0xc/CapacityTester#15]
Hi could you be more specific with the description. Thank you for the app. I want to know what you mean by fake? I know different brand flash drives are often "built" differently so the capacities differ. I want to use your app mainly for testing bad blocks as quickly as possible. Thank you!

**Comment by c0xc** [comment]
Quoting the example from the README file:

_For example, a fake might be sold as "64 GB USB thumb drive" but it would only have a real capacity of 4 GB, everything beyond this limit will be lost._

So the problem that this program is supposed to solve is: You have bought a USB drive and before saving anything on it, you want to **find out if it really has the capacity it claims to have**. There is at least one other program on the market but it takes hours and days (plus it's Windows only) whereas CapacityTester has a quick disk test which only takes a couple of minutes. This type of test is not meant to detect bad blocks.

However, I have just released version 0.6 which allows you to run the disk test in "**full mode**", which means that **it tests the full storage device**, similar to what badblocks does. The disk test is destructive just like `badblocks -w`, except that it currently works in 1M chunks, so it wouldn't report the exact block number. Also, badblocks runs 3 or 4 times by default and the full disk test just goes over the disk once. So if you want to test an hdd that's not quite dead which has a block that sometimes returns corrupted data, such an option might be useful. But if you really have a bad block that's definitely dead, you could use the full disk test to find it (again, as of now, the position of the first error, rounded to 1 MB).

**Comment by lexterror** [comment]
ok, thank you!
