### ISSUE TITLE
feat : Add an estimated time remaining

### ISSUE THREAD

**Issue by fbruand** [c0xc/CapacityTester#18]
Propose adding an estimate of the time remaining in the progress bar for each test stage in CapacityTester. This estimate would allow users to follow the progress of the test and find out the approximate time remaining for each stage.

For example, I'm doing a full test on a 2TB USB stick and I'd like to know the approximate time remaining.

**Comment by c0xc** [comment]
Good idea, thanks.
I will have to slightly redesign that part anyway when I fully separate the new disk test dialog from the old volume test window. So it won't happen right now, but I'll keep this issue open as a reminder.

By the way, have you tried the (quick) disk test, in the advanced menu? If all you want to know is if your usb drive is fake, that test should be able to tell you within minutes. On the other hand, a full test will obviously take a long time.

**Comment by fbruand** [comment]
Hi, sorry I forgot to reply.

The chip I think is in the USB key https://eu.mouser.com/ProductDetail/SanDisk/SDIN7DP2-4G?qs=EgF7oUuTQmpAPyQtQI49Xw%3D%3D (it was in the 2TB one with the same appearance).

If it helps, here are the screen tests I did yesterday to show you.

Quick Test CapacityTester (Advanced - Disk Test) :
![Quick Test CapacityTester](https://github.com/c0xc/CapacityTester/assets/106990203/629669be-764e-4df3-bf3d-d8f7707679a7)

Quick Test AxoFlashTest:
![Quick Test AxoFlashTest](https://github.com/c0xc/CapacityTester/assets/106990203/5c8a19f5-3cf4-4ece-a145-a6a071041432)

I no longer have the results of the full test, so I'm doing the test to find out the difference.

**Comment by fbruand** [comment]
Here is the result of the full test. It's a pity that the quick test is rounded off; perhaps there is a way to obtain a more precise size?

Full Test CapacityTester  (Advanced - Disk Test):
![Full Test CapacityTester](https://github.com/c0xc/CapacityTester/assets/106990203/b7726f38-2f3e-43b7-a661-884cfc55a21a)

An option like AxoFlashTest to create a partition of the actual size might not be a bad idea, but personally, I wouldn't trust such hardware to store valuable data.

Displaying the USB version at which the USB key is recognized (USB 1.0, 2.0, 3.0...) with perhaps the limit of the port on which it is plugged in, like for the one I have, the seller said it was USB 3.0, but when I checked on the KDE info center (the USB key being on a USB 3.0 port), it shows as USB 2.0, whereas if I connect USB 3.0 hardware, it indeed shows as 3.0 on this port.

If any of the ideas I'm suggesting interest you and you want issues for each interesting idea, don't hesitate to let me know.

**Comment by c0xc** [comment]
Thank you very much for your input and feedback and sorry that I'm slow to respond. I'm busy with other projects most of the time but I definitely want to improve the layout soon.

1. I'm going to put it all in one window, so for the (advanced) disk test, the old one that's on the left of your screenshot will be removed. So I'll put some progress bars or something in there and add some timer.
2. At least for the full disk test. The quick disk test works differently and usually finishes within a minute but I'll see what I can do.
3. I've seen that idea in the past, creating a partition within the range that's writable (assuming that range starts at zero which it usually does). However, I would never use such a function and as you say, you wouldn't trust such a device, so it sounds like you wouldn't either. It's easy to reformat the drive (even with CapacityTester) and you'll have a large partition again which goes beyond the real size. Plus fake drives are usually slow, I have one "SSD" which is a slow sd card reader, who would want to use that? So I don't think it's a good idea, it would just lead to bad feelings, mistakes and data loss.
4. Displaying more details about the USB protocol and bus, interesting! I've actually had that idea to add some more debugging tools to CapacityTester but I'll have to see how much information I can get. And it's a separate thing, so I'd suggest you open a separate issue for that.
5. The quick test currently works with GB precision, so it's not that the result is rounded but it was a design decision by me. Theoretically I could change that but what's the benefit? It would be slower, too. And I'm actually quite happy to have that quick test be able to detect a fake within less than a minute. Edit: I see you probably meant "after 3 GB" above the graph. I'll change that.

**Comment by c0xc** [comment]
Please try [v0.7](https://github.com/c0xc/CapacityTester/releases/tag/v0.7).

There's now a time estimate:
![Screenshot_20240811_194948](https://github.com/user-attachments/assets/ac95a8cb-0217-4eef-8ab1-3f96fadcdf5f)

And some info about the USB bus:
![Selection_001](https://github.com/user-attachments/assets/4522408a-bd97-4af3-b32a-af32e967a914)
