### ISSUE TITLE
Install on Ubuntu

### ISSUE THREAD

**Issue by manurafal** [c0xc/CapacityTester#2]
I am sorry I am new to ubuntu and I try to install its application, but I do not get it, could you indicate the steps for all those who started in ubuntu and do not know how to install your application? I have ubuntu 18.4

Thanks a lot

**Comment by c0xc** [comment]
This is a standalone tool, so I have not written an official install routine. If you have a Qt build environment, you should be able to run `qmake && make` to build the binary. Or you could download a release with a pre-compiled binary, for example the first [Debian 7 release](https://github.com/c0xc/CapacityTester/files/120941/CapacityTester_Debian7.tar.gz), but that's not guaranteed to work. Consider it to be a sort of lazy approach - set the executable bit on the file (Caja properties dialog or `chmod +x ~/bin/CapacityTester`) and run it.

To install it manually, I suggest you copy the binary to your `~/bin/` directory and make sure that directory is in your PATH (run `echo $PATH` in a terminal to check). If not, adding the following lines to your profile (`~/.profile`, depending on your setup) would be a typical approach:

    # User specific environment and startup programs
    PATH=$PATH:$HOME/.local/bin:$HOME/bin
    export PATH

**Comment by c0xc** [comment]
Well... Of course, most end users don't have a Qt build environment. And if you don't have the Qt5 libraries installed either (which might be provided by qt5-default), you wouldn't be able to run the binary from the Debian 7 release I mentioned either. As an alternative, I might create another release with a binary linked to a static Qt build.

Anyway. Please clarify your question and copy whatever error messages you're getting.

**Comment by c0xc** [comment]
There's an AppImage executable now. If you think there should be an installable Flatpak, open an issue.
