### ISSUE TITLE
Request: add Windows build

### ISSUE THREAD

**Issue by DeflateAwning** [c0xc/CapacityTester#20]

**Comment by c0xc** [comment]
There's a Windows build binary for the last version:
https://github.com/c0xc/CapacityTester/releases/tag/v0.5

As for the current release, I want to fix the ui, then I'll provide a new Windows build.

**Comment by DeflateAwning** [comment]
Please consider re-opening this issue, and then closing it once the task is done. I only looked at the latest release (as you'd expect), which is why I was confused.

**Comment by c0xc** [comment]
There's now a Windows build available for the new release v0.7:
https://github.com/c0xc/CapacityTester/releases/tag/v0.7
