### ISSUE TITLE
Interupted testing

### ISSUE THREAD

**Issue by mmuruev** [c0xc/CapacityTester#23]
Seems like util cannot be interrupted, which is weird considering how long it takes. Make sense produce predictable files which can be reused (not it complains that it must be remove which is dull). The same for existing files. if I have files on flash make sense assume that they occupied space already, you can check it but it up to user you can verify rest of the space, and make report how much was verified and how much actually occupied by user files.

**Comment by c0xc** [comment]
Not sure if I got that right but I don't see the point of interrupting and resuming a test, the content would have changed in the meantime. And as for files already on the USB flash drive, they can be ignored although the reported offset might then be inaccurate.
