### ISSUE TITLE
Disk Test - Write error after 0MB

### ISSUE THREAD

**Issue by ghost** [c0xc/CapacityTester#24]
Issue running a disk test against a USB / lightning USB stick. It fails instantly after starting.
![image](https://github.com/c0xc/CapacityTester/assets/11243032/4fab34f3-62f4-47f3-af04-3a19e966aac9)
![image](https://github.com/c0xc/CapacityTester/assets/11243032/5654ae41-e357-4b3f-be29-d89182ec88c8)

**Comment by fbruand** [comment]
Hello,

Have you tried copying photos, pdf files or other files to see if they are still readable on the USB flash drive?
I myself have two fake "Samsung" USB sticks at home which apparently have the same symptoms as yours.

If you have the opportunity to test your USB flash drive with other software, such as AxoFlashTest, H2testw or ValiDrive, please let me know.
This will help determine whether the problem lies with the USB flash drive itself or with CapacityTester under Windows.

**Comment by ghost** [comment]
I confirmed the capacity with h2testw, The capacity seems to be valid.
Cheers

**Comment by c0xc** [comment]
Hi, it seems it couldn't even start the test. That selection dialog in your screenshot is actually from the disk test (not the volume test which failed), have you done that? It will wipe your usb stick so you'll have to reformat it afterwards (and if you don't but still have that other volume test open it could explain the error).

**Comment by Juksefantomet** [comment]
Adding a comment here, got the same on Ubuntu. When not running the program as sudo (root / elevated privileges). The program itself clearly stated "We will ask for elevated privileges when needed", but failed instantly and never did ask for sudo elevation.

**Comment by Nathan22211** [comment]
same here on arch linux, I believe this to be a perms issue a bit since the app doesn't ask for sudo on launch, despite some of it's features needing root it seems

**Comment by c0xc** [comment]
To the last two comments: The disk test requires root privileges and if the program is not started as root, it attempts to gain root privileges during the test, in other words this is for convenience. This requires an active PolicyKit agent and sudo setup. Sounds like I'm not catching a failed attempt to gain root in some cases. But note that you can always start CapacityTester as root to avoid this.

**Comment by c0xc** [comment]
Please try [v0.7](https://github.com/c0xc/CapacityTester/releases/tag/v0.7), reopen this bug report if you're still unable to start the test. The volume test, shown in the screenshot (window on the right), is still available after selecting a storage device, where the partitions are listed (there should be 1 if it's formatted), click on "Filesystem test".
But it's now recommended to run a raw disk test instead.

A possible issue when starting via sudo (referring to the last comments) has also been addressed.
