### ISSUE TITLE
Stuck at 100% initialization

### ISSUE THREAD

**Issue by DuckersMcQuack** [c0xc/CapacityTester#25]
Testing a "2TB" i bought for 3 euros for shits, and wanted to see how much capacity it had, but it's been stuck at initializing for 40 minutes, is that normal? Or when is it set to be timed out/error out to say "this capacity is fake"?

![image](https://github.com/c0xc/CapacityTester/assets/9039370/8bd9c1de-28b4-40fb-b9db-954ffb683efd)

**Comment by c0xc** [comment]
Hi [DuckersMcQuack](https://github.com/DuckersMcQuack), yes, this may be "normal" in the sense that some fake drives are really slow. I had one "SSD" running for a week one time (another time, it finished within hours).

The volume test you are using is using files (on top of a mounted disk / volume), so it relies on the underlying filesystem and the operating system and has no insight into low-level communications. So there's no additional timeout either.

What I would recommend, especially for a (fake) drive of that size, is the "destructive" disk test, in the Advanced menu.

**Comment by c0xc** [comment]
Please try [v0.7](https://github.com/c0xc/CapacityTester/releases/tag/v0.7), run the raw disk test (which is now the default, available after selecting a device, not hidden under "Advanced" anymore). Closing issue.
