### ISSUE TITLE
When I open the Capacity Tester appimage app the Impression image writing app appears. ??

### ISSUE THREAD

**Issue by anandananda** [c0xc/CapacityTester#26]
Capacity_Tester-x86_64.AppImage, 28.1MB. Downloaded on 30Apr24
Is this expected? Where is the Capacity Tester UI? Let me know if I'm missing something. I'm running Linux / Tumbleweed / Gnome / Wayland on an AMD Ryzen laptop.

**Comment by c0xc** [comment]
So you double-click Capacity Tester and something else opens? This would be the first time I've heard that. Does it also happen when you run it from the cli?

**Comment by anandananda** [comment]
Hi. I just tried it and it's working. I must have done something wrong the
first time. PEBCAC.
