### ISSUE TITLE
appimage package

### ISSUE THREAD

**Issue by SalehGNUTUX** [c0xc/CapacityTester#5]
I hope that the development of the program will continue, especially since the GNU / Linux system lacks a similar program that works via the graphical interface, and I hope that the availability of a version appimage which gives great ease in running the program on various distributions without the need to install it. Thank you

**Comment by c0xc** [comment]
Since the program does not need any unusual libraries, the pre-compiled binary should already work on most systems.
I have added an AppImage executable file. It can be found in the latest [release](https://github.com/c0xc/CapacityTester/releases/tag/v0.3).
