### ISSUE TITLE
Representation of the numbers

### ISSUE THREAD

**Issue by kajo8** [c0xc/CapacityTester#7]
I have make a test with an fast USB-Stick. He is show me the reading speed as "1.5e+02 MB/s".
Could you change it in a way that the program is showing me something like: "150MByte/s"

**Comment by c0xc** [comment]
Thanks for your request! An updated (Linux) build is available here:
https://github.com/c0xc/CapacityTester/suites/11562147505/artifacts/598848761

**Comment by kajo8** [comment]
Thank you, it looks good now!
